const stories = [
  { id: 1, title: "一杯温暖的豆浆", level: "HSK 2", words: 128, paragraphs: ["每天早上，李明都去街角的小店买一杯豆浆。店里的阿姨总是笑着说：“早上好，今天也加一个鸡蛋吗？”", "一个下雨的早晨，李明发现自己忘了带伞。阿姨把一把蓝色的伞递给他：“拿去用吧，明天还给我就好。”", "第二天，李明带着伞回来，还买了两杯热豆浆。他把其中一杯送给阿姨。小店里飘着豆浆的香味，两个人都笑了。"], translation: ["Every morning, Li Ming goes to the little shop on the corner to buy a cup of soy milk. The auntie at the shop always smiles and says, “Good morning! Would you like an egg today too?”", "One rainy morning, Li Ming realized he had forgotten his umbrella. The auntie handed him a blue one. “Take it. Just bring it back tomorrow.”", "The next day, Li Ming returned with the umbrella and bought two cups of warm soy milk. He gave one to the auntie. The little shop smelled of soy milk, and they both smiled."], vocabulary: [{word:"街角",pinyin:"jiējiǎo",meaning:"street corner",type:"名词",example:"我家附近的街角有一家书店。"},{word:"总是",pinyin:"zǒngshì",meaning:"always; every time",type:"副词",example:"他总是很早到学校。"},{word:"递",pinyin:"dì",meaning:"to hand; to pass",type:"动词",example:"请把那本书递给我。"},{word:"其中",pinyin:"qízhōng",meaning:"among them; one of",type:"代词",example:"这些苹果中，我拿了其中一个。"}], grammar:[{pattern:"把 + 东西 + 动词",explain:"“把”字句把动作的对象提前，强调对这个东西做了什么。",example:"阿姨把一把蓝色的伞递给他。"},{pattern:"还（hái） + 动词",explain:"“还”可以表示动作继续，或把借来的东西归还。这里表示“归还”。",example:"明天还给我就好。"}], questions:[{q:"李明每天早上去哪里？",options:["学校", "街角的小店", "公园"],answer:1},{q:"阿姨把什么借给了李明？",options:["一把伞", "一本书", "一辆自行车"],answer:0}], answers:["街角的小店。","一把蓝色的伞。"]},
  { id: 2, title: "公园里的新朋友", level: "HSK 2", words: 116, paragraphs: ["周末，安娜去公园散步。她看到一个小男孩在找东西，便走过去问：“你在找什么？”", "小男孩说，他的红色气球飞到树上了。安娜请公园的工作人员来帮忙。不一会儿，气球就拿下来了。", "小男孩开心地说：“谢谢你！”安娜笑着回答：“不客气。我们一起去看湖边的小鸭子吧。”"], translation:["On the weekend, Anna went for a walk in the park. She saw a little boy looking for something, so she went over and asked, “What are you looking for?”","The boy said his red balloon had flown into a tree. Anna asked a park worker to help. Before long, the balloon was brought down.","The boy happily said, “Thank you!” Anna smiled and replied, “You’re welcome. Let’s go see the little ducks by the lake together.”"],vocabulary:[{word:"散步",pinyin:"sànbù",meaning:"to take a walk",type:"动词",example:"晚饭以后，我们一起去散步。"},{word:"工作人员",pinyin:"gōngzuò rényuán",meaning:"staff member",type:"名词",example:"工作人员帮助了我们。"},{word:"不一会儿",pinyin:"bù yíhuìr",meaning:"before long",type:"时间词",example:"他等了一会儿，朋友就来了。"},{word:"一起",pinyin:"yìqǐ",meaning:"together",type:"副词",example:"我们一起学习中文。"}],grammar:[{pattern:"便 + 动词",explain:"“便”表示紧接着发生的动作，语气比“就”稍正式。",example:"她看到小男孩，便走过去问。"},{pattern:"请 + 人 + 做事",explain:"表示请求或请某人帮忙做一件事。",example:"安娜请工作人员来帮忙。"}],questions:[{q:"小男孩在找什么？",options:["小狗", "红色气球", "书包"],answer:1},{q:"气球最后怎么样了？",options:["飞走了", "被拿下来了", "掉进湖里了"],answer:1}],answers:["红色气球。","工作人员帮忙把气球从树上拿下来了。"]},
  { id: 3, title: "奶奶的生日", level: "HSK 3", words: 143, paragraphs: ["星期天是奶奶的生日。小雨想给奶奶一个惊喜，就和爸爸一起学着做蛋糕。", "他们先把鸡蛋、牛奶和面粉放在碗里，然后慢慢地搅拌。虽然蛋糕的样子不太好看，但是房间里都是甜甜的香味。", "奶奶打开门，看见桌上的蛋糕，高兴地抱住了小雨。她说：“这是我收到的最好的礼物。”"],translation:["Sunday was Grandma’s birthday. Xiaoyu wanted to surprise her, so she learned to make a cake with her dad.","First they put eggs, milk, and flour into a bowl, then slowly mixed them together. Although the cake did not look very nice, the room was filled with a sweet smell.","Grandma opened the door and saw the cake on the table. She happily hugged Xiaoyu. “This is the best gift I’ve ever received,” she said."],vocabulary:[{word:"惊喜",pinyin:"jīngxǐ",meaning:"surprise",type:"名词",example:"我准备了一个小惊喜。"},{word:"搅拌",pinyin:"jiǎobàn",meaning:"to stir; to mix",type:"动词",example:"请把牛奶和鸡蛋搅拌均匀。"},{word:"虽然",pinyin:"suīrán",meaning:"although",type:"连词",example:"虽然下雨了，我们还是去了。"},{word:"收到",pinyin:"shōudào",meaning:"to receive",type:"动词",example:"我收到了朋友的来信。"}],grammar:[{pattern:"虽然……但是……",explain:"连接两个意思相反或有转折关系的分句。",example:"虽然蛋糕不太好看，但是味道很好。"},{pattern:"先……然后……",explain:"按顺序介绍两个或多个连续动作。",example:"先把材料放进碗里，然后搅拌。"}],questions:[{q:"小雨和谁一起做蛋糕？",options:["妈妈", "爸爸", "朋友"],answer:1},{q:"奶奶觉得蛋糕是什么？",options:["最好的礼物", "一个惊喜", "太甜了"],answer:0}],answers:["小雨和爸爸一起做蛋糕。","奶奶觉得蛋糕是她收到的最好的礼物。"]}
];
const extras=Array.from({length:7},(_,i)=>({id:i+4,title:`中文故事 ${String(i+4).padStart(2,"0")}`,level:i<3?"HSK 3":"HSK 4",words:120+i*9,paragraphs:["这篇故事正在准备中。你可以先阅读其他故事，词语、语法和练习功能都已经可以体验。"],translation:["This story is being prepared. You can read another story for now; the vocabulary, grammar, and practice sections are ready to explore."],vocabulary:[],grammar:[],questions:[],answers:[]}));
stories.push(...extras);
stories[0] = {
  id: 1,
  title: "一座为动物建的桥",
  englishTitle: "A Bridge Built for Animals",
  level: "HSK 3–5",
  words: 408,
  paragraphs: [
    "在广西，平陆运河刚刚建成。运河打通之后，当地的交通变得比以前方便很多，运送货物也更快更多了。人们注意到，在运河上有一座特别的桥，它没有坚硬的路面，也没有路灯，它连接的不是村庄，而是两边的大山。原来，这是一座专门为了动物建的桥。有了这座桥，运河两边的树林和草地不再被分开，动物的活动路线不会被完全切断，它们仍然可以找到食物，繁殖后代。",
    "在运河开始使用的时候，这座动物桥也建好了。桥全长约240米，宽20米，整座桥都按照原来山里的树林的环境来设计，非常适合狐狸、野猫、松鼠等动物的生活。为了让桥看起来和山地的环境一样，设计师们把桥的两边和山连接的地方做得特别宽，上面满是和周围一样的树和草，还有动物们喜欢的各种果树。甚至连泥土都是从同一座山挖去的。几个月过去了，我们看到桥上的树木开始长高，最近，桥上开始出现动物的脚印。看来是“甲方”过来验收了。不久我们将会看到，船在桥下开过，动物在桥上跑动。"
  ],
  translation: [
    "In Guangxi, the Pinglu Canal has just been completed. After the canal was opened, local transportation became much more convenient than before, and goods are transported faster and in larger quantities. People noticed that there is a special bridge over the canal. It has no hard pavement, nor streetlights, and it connects not villages, but the mountains on both sides. As it turns out, this is a bridge specially built for animals. With this bridge, the forests and grasslands on both sides of the canal are no longer separated, and animals' activity routes will not be completely cut off, allowing them to still find food and reproduce.",
    "When the canal came into use, this animal bridge was also completed. The bridge is about 240 meters long and 20 meters wide. The entire bridge was designed according to the original forest environment in the mountains, making it very suitable for the life of animals such as foxes, wild cats, and squirrels. In order to make the bridge look the same as the mountain environment, designers made the connection areas on both sides of the bridge particularly wide, planting them full of trees and grass that are the same as those around, as well as various fruit trees that animals like. Even the soil was dug from the same mountain. Months passed, and we saw the trees on the bridge starting to grow taller. Recently, animal footprints have begun to appear on the bridge. It seems the “clients” have come for inspection. Soon we will see ships passing under the bridge and animals running on top of it."
  ],
  vocabulary: [
    {word:"一样",pinyin:"yíyàng",meaning:"same / alike",type:"HSK 3",englishTerms:["the same"],example:"这座桥和山地的环境一样。"},
    {word:"船",pinyin:"chuán",meaning:"boat / ship",type:"HSK 3",englishTerms:["ships"],example:"船在桥下开过。"},
    {word:"生活",pinyin:"shēnghuó",meaning:"life / to live",type:"HSK 3",englishTerms:["life"],example:"这座桥适合动物生活。"},
    {word:"草",pinyin:"cǎo",meaning:"grass",type:"HSK 3",englishTerms:["grasslands","grass"],example:"桥上种着树和草。"},
    {word:"地方",pinyin:"dìfāng",meaning:"place / location",type:"HSK 3",englishTerms:["connection areas"],example:"桥和山连接的地方很宽。"},
    {word:"为了",pinyin:"wèile",meaning:"in order to / for",type:"HSK 3",englishTerms:["in order to"],example:"为了保护动物，人们建了这座桥。"},
    {word:"交通",pinyin:"jiāotōng",meaning:"traffic / transportation",type:"HSK 4",englishTerms:["transportation"],example:"运河打通后，当地交通更方便了。"},
    {word:"树林",pinyin:"shùlín",meaning:"woods / forest",type:"HSK 4",englishTerms:["forests","forest"],example:"桥按照山里的树林环境来设计。"},
    {word:"桥",pinyin:"qiáo",meaning:"bridge",type:"HSK 4",englishTerms:["bridge"],example:"这是一座为动物建的桥。"},
    {word:"满",pinyin:"mǎn",meaning:"full / filled",type:"HSK 4",englishTerms:["full of"],example:"桥上满是树和草。"},
    {word:"食物",pinyin:"shíwù",meaning:"food",type:"HSK 4",englishTerms:["food"],example:"动物可以在树林里找到食物。"},
    {word:"各种",pinyin:"gèzhǒng",meaning:"various / all kinds of",type:"HSK 4",englishTerms:["various"],example:"桥上有各种动物喜欢的果树。"},
    {word:"宽",pinyin:"kuān",meaning:"wide / broad",type:"HSK 5",englishTerms:["wide"],example:"这座桥宽20米。"},
    {word:"建",pinyin:"jiàn",meaning:"to build / construct",type:"HSK 5",englishTerms:["built"],example:"这是一座专门为动物建的桥。"},
    {word:"设计",pinyin:"shèjì",meaning:"to design / design",type:"HSK 5",englishTerms:["designed"],example:"设计师按照山里的环境来设计这座桥。"},
    {word:"连接",pinyin:"liánjiē",meaning:"to connect / join",type:"HSK 5",englishTerms:["connects","connection"],example:"这座桥连接了运河两边的大山。"}
  ],
  grammar: [
    {pattern:"刚刚 (gānggāng) · just did something · HSK 4-01",explain:"副词，表示动作或情况发生不久。 An adverb indicating that an action or situation happened just a moment ago.",example:"在广西，平陆运河刚刚建成。 / In Guangxi, the Pinglu Canal has just been completed。我们刚刚学完第三课。 / We have just finished studying Lesson 3."},
    {pattern:"和……一样 (hé…yíyàng) · the same as · HSK 3-09",explain:"结构：A + 和 + B + 一样，用来比较两者相同。 Structure: A + 和 + B + 一样. Used to indicate that two things are the same.",example:"为了让桥看起来和山地的环境一样，设计师们把桥的两边做得特别宽。 / Designers made both sides of the bridge wide so it would look the same as the mountain environment。我和你们一样，都不会说中文。 / I, the same as you, cannot speak Chinese。"}
  ],
  questions: [
    {q:"这座特别的桥是为谁建的？",options:["游客","村民","动物","船员"],answer:2},
    {q:"为什么要建这座动物桥？",options:["为了让船开得更快","为了让运河两边的动物活动路线不会被完全切断","为了让游客可以在桥上散步","为了方便村民种树"],answer:1},
    {q:"这座动物桥大约有多长？",options:["120米","180米","200米","240米"],answer:3},
    {q:"设计师为什么在桥上种和周围一样的树和草？",kind:"short",answer:"为了让桥看起来和山地环境一样，更适合动物生活。"},
    {q:"最近动物桥上出现了什么？",kind:"short",answer:"出现了动物的脚印。"}
  ],
  answers:["动物。","为了让运河两边的动物活动路线不会被完全切断。","240米。","为了让桥看起来和山地环境一样，更适合动物生活。","出现了动物的脚印。"]
};
const select=document.querySelector("#story-select"), panel=document.querySelector("#study-panel"),tabs=[...document.querySelectorAll(".tab")];let currentStory=stories[0],currentTab="vocabulary",largeText=false,showTranslation=true;
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
stories.forEach(s=>{const o=document.createElement("option");o.value=s.id;o.textContent=`故事 ${String(s.id).padStart(2,"0")} · ${s.title}`;select.append(o)});
function renderStory(){document.querySelector("#story-title").textContent=currentStory.englishTitle?`${currentStory.title} · ${currentStory.englishTitle}`:currentStory.title;document.querySelector("#story-count").textContent=`约 ${currentStory.words} 字`;document.querySelector("#story-level").textContent=currentStory.level;document.querySelector("#reading-progress").textContent=`故事 ${String(currentStory.id).padStart(2,"0")} / 10`;const vocabWords=currentStory.vocabulary.map(v=>v.word).sort((a,b)=>b.length-a.length);const wordPattern=vocabWords.length?new RegExp(`(${vocabWords.join("|")})`,"g"):null;document.querySelector("#story-chinese").innerHTML=currentStory.paragraphs.map(p=>`<p>${escapeHtml(p).replace(wordPattern||/$^/g,match=>{const word=currentStory.vocabulary.find(v=>v.word===match);const hskClass=word?.type.toLowerCase().replace(/[^a-z0-9]/g,"")||"";return `<span class="story-word ${hskClass}" tabindex="0" title="${escapeHtml(word?.type||"")} · 点击查看词语">${match}</span>`})}</p>`).join("");const englishTerms=currentStory.vocabulary.flatMap(v=>(v.englishTerms||[]).map(term=>({term,word:v.word}))).sort((a,b)=>b.term.length-a.term.length);const englishPattern=englishTerms.length?new RegExp(`(${englishTerms.map(x=>x.term).join("|")})`,"gi"):null;document.querySelector("#story-english").innerHTML=currentStory.translation.map(p=>`<p>${escapeHtml(p).replace(englishPattern||/$^/gi,match=>`<span class="story-english-word" title="${escapeHtml(englishTerms.find(x=>x.term.toLowerCase()===match.toLowerCase())?.word||"")}">${match}</span>`)}</p>`).join("");select.value=currentStory.id;renderPanel()}
function vocabulary(){return `<div class="panel-kicker">HSK VOCABULARY</div><h2 class="panel-title">HSK 重点词语 <span class="count-note">${currentStory.vocabulary.length} 个重点词</span></h2><div class="vocab-list">${currentStory.vocabulary.map(v=>{const hskClass=v.type.toLowerCase().replace(/[^a-z0-9]/g,"");return `<div class="vocab-item"><div><span class="vocab-word">${escapeHtml(v.word)}</span><span class="pinyin">${escapeHtml(v.pinyin)}</span></div><div class="vocab-meaning">${escapeHtml(v.meaning)}</div><span class="part-speech ${hskClass}">${escapeHtml(v.type)}</span></div>`}).join("")||`<p class="empty-note">这篇故事的词语整理还在准备中。</p>`}</div>`}
function grammar(){return `<div class="panel-kicker">LANGUAGE POINTS</div><h2 class="panel-title">Language Points</h2>${currentStory.grammar.map(g=>`<div class="grammar-block"><div class="grammar-pattern">${escapeHtml(g.pattern)}</div><div class="grammar-explain">${escapeHtml(g.explain)}</div><div class="grammar-example">${escapeHtml(g.example)}</div></div>`).join("")||`<p class="empty-note">这篇故事的语言点还在准备中。</p>`}`}
function practice(){return `<div class="panel-kicker">EXERCISES</div><h2 class="panel-title">读懂故事了吗？</h2>${currentStory.questions.map((q,i)=>q.kind==="short"?`<div class="question short-question"><div class="question-title"><span class="question-number">0${i+1}</span> ${escapeHtml(q.q)}</div><textarea class="short-answer" name="q${i}" rows="2" aria-label="第${i+1}题答案" placeholder="写下你的答案"></textarea></div>`:`<fieldset class="question"><legend class="question-title"><span class="question-number">0${i+1}</span> ${escapeHtml(q.q)}</legend>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"/><span>${String.fromCharCode(65+j)}.</span> ${escapeHtml(o)}</label>`).join("")}</fieldset>`).join("")||`<p class="empty-note">这篇故事的练习题还在准备中。</p>`}<button class="check-button" id="check-answers" type="button">检查答案 <span>→</span></button><div id="quiz-feedback" class="quiz-feedback" aria-live="polite"></div>`}
function answers(){return `<div class="panel-kicker">ANSWERS</div><h2 class="panel-title">参考答案与提示</h2>${currentStory.answers.map((a,i)=>`<div class="answer-row"><div class="answer-q">问题 0${i+1} · ${escapeHtml(currentStory.questions[i]?.q||"")}</div><div class="answer-a">${escapeHtml(a)}</div><div class="answer-note">回到故事中找一找相关信息，试着用自己的话复述。</div></div>`).join("")||`<p class="empty-note">这篇故事的答案还在准备中。</p>`}`}
function renderPanel(){const renderers={vocabulary,grammar,practice,answers};panel.innerHTML=renderers[currentTab]();tabs.forEach(t=>{const active=t.dataset.tab===currentTab;t.classList.toggle("active",active);t.setAttribute("aria-selected",active)});const check=document.querySelector("#check-answers");if(check)check.addEventListener("click",checkAnswers)}
function checkAnswers(){const qs=currentStory.questions, feedback=document.querySelector("#quiz-feedback");const missing=qs.some((q,i)=>q.kind==="short"?!document.querySelector(`textarea[name="q${i}"]`)?.value.trim():!document.querySelector(`input[name="q${i}"]:checked`));if(missing){feedback.textContent="先完成所有题目，再来检查答案吧。";feedback.className="quiz-feedback visible";return}const objective=qs.map((q,i)=>({q,i})).filter(x=>x.q.kind!=="short"),score=objective.reduce((n,{q,i})=>n+(Number(document.querySelector(`input[name="q${i}"]:checked`).value)===q.answer?1:0),0),shortCount=qs.filter(q=>q.kind==="short").length;feedback.textContent=shortCount?`选择题答对 ${score} / ${objective.length} 题；简答题已完成 ${shortCount} 题。切换到 D「Answers」对照参考答案。`:`答对 ${score} / ${objective.length} 题。${score===objective.length?"太棒了！":"可以切换到 D「Answers」看看解析。"}`;feedback.className="quiz-feedback visible"}
select.addEventListener("change",()=>{currentStory=stories.find(s=>s.id===Number(select.value));renderStory()});tabs.forEach(t=>t.addEventListener("click",()=>{currentTab=t.dataset.tab;renderPanel()}));document.querySelector("#next-tab").addEventListener("click",()=>{const order=["vocabulary","grammar","practice","answers"];currentTab=order[(order.indexOf(currentTab)+1)%order.length];renderPanel()});document.querySelector("#font-toggle").addEventListener("click",e=>{largeText=!largeText;document.querySelector("#story-chinese").classList.toggle("large-text",largeText);e.currentTarget.innerHTML=largeText?'字号 <span>小</span>':'字号 <span>大</span>'});document.querySelector("#translation-toggle").addEventListener("click",e=>{showTranslation=!showTranslation;document.querySelector("#story-english").classList.toggle("translation-hidden",!showTranslation);e.currentTarget.textContent=showTranslation?"隐藏译文":"显示译文"});document.querySelector("#story-chinese").addEventListener("click",e=>{if(e.target.classList.contains("story-word")){const w=currentStory.vocabulary.find(v=>v.word===e.target.textContent);if(w){currentTab="vocabulary";renderPanel();const hit=[...panel.querySelectorAll(".vocab-word")].find(n=>n.textContent===w.word);hit?.closest(".vocab-item")?.scrollIntoView({behavior:"smooth",block:"nearest"});}}});
renderStory();
